### ISSUE TITLE
Clarify position of security category

### ISSUE THREAD

**Issue by lucasgonze** [commitizen/conventional-commit-types#25]
It's not clear from the descriptions of the categories whether security fixes are a bug, enhancement, or chore, or possibly a new category to be added.

**Comment by AndersDJohnson** [comment]
@lucasgonze Thanks for raising this issue! I don't necessarily disagree, though, per this project README, we are pretty closely aligned with Angular conventions (https://github.com/angular/angular/blob/main/CONTRIBUTING.md#type). I would think security fixes to 1st party source code would be `fix` in most cases. If it's an upgrade to a 3rd party dependency, Angular tends to use `build`, which is why that has the description `Changes that affect the build system or external dependencies`. Thoughts?

**Comment by lucasgonze** [comment]
I use "chore" most of the time, because it isn't wrong, even though it isn't right either. You can say the same about "fix" and "build." But that suggests the type keyword is creating noise rather than signal.

**Comment by AndersDJohnson** [comment]
Fair point @lucasgonze. Still, I think we won't try to reinvent the wheel here. Thanks though!
